=== MarsYun/komodo/plugins/org.komodo.core/src/org/komodo/repository/komodoValidation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.jboss.org/tools/komodo/validation/2015"
    targetNamespace="http://www.jboss.org/tools/komodo/validation/2015"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified"
    xmlns:tko="http://www.jboss.org/tools/komodo/validation/2015">

    <!-- -->
    <!-- A set of rules that validate nodes of specific types by looking at properties and child nodes. -->
    <!-- -->
    <xs:element name="validationRuleSet">
        <xs:annotation>
            <xs:documentation>A set of Komodo validation rules.</xs:documentation>
        </xs:annotation>

        <xs:complexType>
            <xs:sequence>
                <xs:element
                    name="description"
                    type="localizedMessageType"
                    minOccurs="1"
                    maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>One or more locale-specific messages describing this validation rule set.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>

                <xs:choice
                    minOccurs="1"
                    maxOccurs="unbounded">

                    <!-- Rules for node types and mixins -->
                    <xs:element
                        ref="nodeValidation"
                        maxOccurs="unbounded">
                    </xs:element>

                    <!-- Rules for global properties (common but not found in a mixin) -->
                    <xs:element
                        ref="propertyValidation"
                        maxOccurs="unbounded">
                    </xs:element>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>

        <!-- Make sure the locale is unique for the rule set descriptions -->
        <xs:unique name="ruleSetDescriptionLocaleKey">
            <xs:selector xpath="tko:description" />
            <xs:field xpath="@locale" />
        </xs:unique>

        <!-- Make sure the JCR name attribute is unique across all validations -->
        <xs:unique name="idKey">
            <xs:selector xpath=".//*" />
            <xs:field xpath="@jcrName" />
        </xs:unique>
    </xs:element>

    <!-- -->
    <!-- A node type and mixin validation. -->
    <!-- -->
    <xs:element
        name="nodeValidation"
        type="nodeValidationType">
        <xs:annotation>
            <xs:documentation>A collection of node type validations.</xs:documentation>
        </xs:annotation>

        <!-- Make sure the locale is unique for the node validation message elements -->
        <xs:unique name="nodeValidationMessageLocaleKey">
            <xs:selector xpath="tko:message" />
            <xs:field xpath="@locale" />
        </xs:unique>
    </xs:element>

    <!-- -->
    <!-- A property validation. -->
    <!-- -->
    <xs:element
        name="propertyValidation"
        type="propertyValidationType">
        <xs:annotation>
            <xs:documentation>Validation rules for a property.</xs:documentation>
        </xs:annotation>

        <!-- Make sure the locale is unique for the property validation message elements -->
        <xs:unique name="propertyValidationMessageLocaleKey">
            <xs:selector xpath="tko:message" />
            <xs:field xpath="@locale" />
        </xs:unique>
    </xs:element>

    <!-- -->
    <!-- Validates the properties and child node instances of nodes of a specific type. -->
    <!-- -->
    <xs:complexType name="nodeValidationType">
        <xs:complexContent>
            <xs:extension base="jcrValidationType">
                <xs:choice
                    minOccurs="1"
                    maxOccurs="unbounded">
                    <xs:element
                        name="nameValidation"
                        maxOccurs="1"
                        type="stringRuleType">
                        <xs:annotation>
                            <xs:documentation>Validates the names of the nodes of this type.</xs:documentation>
                        </xs:annotation>
                    </xs:element>

                    <xs:element
                        name="childValidation"
                        maxOccurs="unbounded"
                        type="childValidationType">
                        <xs:annotation>
                            <xs:documentation>Validation rules for child node types.</xs:documentation>
                        </xs:annotation>
                    </xs:element>

                    <xs:element
                        ref="propertyValidation"
                        maxOccurs="unbounded">
                    </xs:element>
                </xs:choice>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- -->
    <!-- Validates the existence of child nodes of a specific type. -->
    <!-- -->
    <xs:complexType name="childValidationType">
        <xs:complexContent>
            <xs:extension base="jcrValidationType">
                <xs:choice
                    minOccurs="1"
                    maxOccurs="4">
                    <xs:element
                        name="requiredValidation"
                        maxOccurs="1"
                        type="requiredRuleType">
                        <xs:annotation>
                            <xs:documentation>Indicates that a child of this node type must exist.</xs:documentation>
                        </xs:annotation>
                    </xs:element>

                    <xs:element
                        name="nameValidation"
                        maxOccurs="1"
                        type="stringRuleType">
                        <xs:annotation>
                            <xs:documentation>Validates the names of the child nodes of this type.</xs:documentation>
                        </xs:annotation>
                    </xs:element>

                    <xs:element
                        name="relationshipValidation"
                        maxOccurs="1"
                        type="relationshipRuleType">
                        <xs:annotation>
                            <xs:documentation>Validates relationships with property values or other child nodes.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>

                    <xs:element
                        name="childCountValidation"
                        maxOccurs="1"
                        type="numberRuleType">
                        <xs:annotation>
                            <xs:documentation>Validates the number of child nodes of this type.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:choice>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- -->
    <!-- Validates a specific property. -->
    <!-- -->
    <xs:complexType name="propertyValidationType">
        <xs:complexContent>
            <xs:extension base="jcrValidationType">
                <xs:choice
                    minOccurs="1"
                    maxOccurs="4">
                    <xs:element
                        name="requiredValidation"
                        maxOccurs="1"
                        type="requiredRuleType">
                        <xs:annotation>
                            <xs:documentation>Indicates that this property must have a value.</xs:documentation>
                        </xs:annotation>
                    </xs:element>

                    <xs:element
                        name="valueValidation"
                        maxOccurs="1"
                        type="stringRuleType">
                        <xs:annotation>
                            <xs:documentation>Validates the value.</xs:documentation>
                        </xs:annotation>
                    </xs:element>

                    <xs:element
                        name="relationshipValidation"
                        maxOccurs="1"
                        type="relationshipRuleType">
                        <xs:annotation>
                            <xs:documentation>Validates relationships with other property values or child nodes.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>

                    <xs:element
                        name="valueRangeValidation"
                        maxOccurs="1"
                        type="numberRuleType">
                        <xs:annotation>
                            <xs:documentation>Validates a number value is within a minimum and maximum range.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:choice>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- -->
    <!-- A base type for validation that is based on a JCR property, node type, or mixin. -->
    <!-- -->
    <xs:complexType name="jcrValidationType">
        <xs:sequence>
            <xs:element
                name="message"
                type="localizedMessageType"
                minOccurs="1"
                maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>One or more locale-specific messages describing this validation.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>

        <xs:attribute
            name="jcrName"
            type="xs:QName"
            use="required">
            <xs:annotation>
                <xs:documentation>The fully-qualified name of the JCR property, node type, or mixin being validated.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <!-- -->
    <!-- A rule that indicates a property value or child node of a certain type must exist. -->
    <!-- -->
    <xs:complexType name="requiredRuleType">
        <xs:complexContent>
            <xs:extension base="ruleType"></xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- -->
    <!-- A rule that validates a value based on if it matches a pattern. -->
    <!-- -->
    <xs:complexType name="stringRuleType">
        <xs:complexContent>
            <xs:extension base="ruleType">
                <xs:sequence>
                    <xs:element
                        name="pattern"
                        type="xs:string"
                        minOccurs="1"
                        maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation>A regular expression pattern used in determining if a value is valid.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- -->
    <!-- A rule that validates a number falls within a range or validates the number of child nodes of a specific type. -->
    <!-- -->
    <xs:complexType name="numberRuleType">
        <xs:complexContent>
            <xs:extension base="ruleType">
                <xs:choice
                    minOccurs="1"
                    maxOccurs="2">
                    <xs:element
                        name="minValue"
                        type="boundaryType"
                        maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation>The smallest, or minimum, value allowed.</xs:documentation>
                        </xs:annotation>
                    </xs:element>

                    <xs:element
                        name="maxValue"
                        type="boundaryType"
                        maxOccurs="1">
                        <xs:annotation>
                            <xs:documentation>The largest, or maximum, value allowed.</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:choice>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- -->
    <!-- A rule that validates the existence or absense of other properties or child nodes. -->
    <!-- -->
    <xs:complexType name="relationshipRuleType">
        <xs:complexContent>
            <xs:extension base="ruleType">
                <xs:choice
                    minOccurs="1"
                    maxOccurs="unbounded">
                    <xs:element
                        name="propDoesExist"
                        type="xs:QName"
                        minOccurs="0"
                        maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation>A fully-qualified JCR name of a property that must exist when this property or child
                                node type exists.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>

                    <xs:element
                        name="propIsAbsent"
                        type="xs:QName"
                        minOccurs="0"
                        maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation>A fully-qualified JCR name of a property that must NOT exist when this property or
                                child node type exists.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>

                    <xs:element
                        name="childDoesExist"
                        type="xs:QName"
                        minOccurs="0"
                        maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation>A child must exist with this fully-qualified JCR node type or mixin name.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>

                    <xs:element
                        name="childIsAbsent"
                        type="xs:QName"
                        minOccurs="0"
                        maxOccurs="unbounded">
                        <xs:annotation>
                            <xs:documentation>A child must NOT exist with this fully-qualified JCR node type or mixin name.
                            </xs:documentation>
                        </xs:annotation>
                    </xs:element>
                </xs:choice>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- -->
    <!-- The base type for all validation rules. -->
    <!-- -->
    <xs:complexType name="ruleType">
        <xs:sequence>
            <xs:element
                name="message"
                type="localizedMessageType"
                minOccurs="1"
                maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>One or more locale-specific messages for when rule evaluation fails.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>

        <xs:attribute
            name="id"
            type="xs:QName"
            use="required">
            <xs:annotation>
                <xs:documentation>The fully-qualified JCR name of the property being validated.</xs:documentation>
            </xs:annotation>
        </xs:attribute>

        <xs:attribute
            name="enabled"
            type="xs:boolean"
            default="true">
            <xs:annotation>
                <xs:documentation>Indicates if this rule is enabled and should be evaluated.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <!-- -->
    <!-- A boundary value (such as minimum or maximum). -->
    <!-- -->
    <xs:complexType name="boundaryType">
        <xs:annotation>
            <xs:documentation>A numeric lower or upper boundary value that is inclusive or exclusive.</xs:documentation>
        </xs:annotation>

        <xs:simpleContent>
            <xs:extension base="boundaryValueType">
                <xs:attribute
                    name="inclusive"
                    type="xs:boolean"
                    default="true">
                    <xs:annotation>
                        <xs:documentation>Indicates if the boundary value is inclusive.</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- -->
    <!-- A non-empty message and a locale that indicates the language of the message. -->
    <!-- -->
    <xs:complexType name="localizedMessageType">
        <xs:annotation>
            <xs:documentation>A message that has been translated to the language of the specified locale.</xs:documentation>
        </xs:annotation>

        <xs:simpleContent>
            <xs:extension base="nonEmptyStringType">
                <xs:attribute
                    name="locale"
                    type="xs:language"
                    use="required">
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- -->
    <!-- A non-empty string. -->
    <!-- -->
    <xs:simpleType name="nonEmptyStringType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>

    <!-- -->
    <!-- A min or max value string. -->
    <!-- -->
    <xs:simpleType name="boundaryValueType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]+(.[0-9]+)?" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== MarsYun/komodo/tests/org.komodo.core.test/resources/validationAllConstructs.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<validationRuleSet
    xmlns:val="http://www.jboss.org/tools/komodo/validation/2015"
    xmlns:ddl="http://www.modeshape.org/ddl/1.0"
    xmlns:vdb="http://www.metamatrix.com/metamodels/VirtualDatabase"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.jboss.org/tools/komodo/validation/2015 http://www.jboss.org/tools/komodo/validation/2015/komodoValidation.xsd"
    xmlns="http://www.jboss.org/tools/komodo/validation/2015">

    <description locale="en">This is a test validation file.</description>
    <description locale="es">Este es un archivo de validación de pruebas.</description>

    <nodeValidation jcrName="vdb:virtualDatabase">
        <message locale="en">Validation rules for the 'vdb:virtualDatabase' node type.</message>
        <message locale="es">Las reglas de validación para el tipo de nodo 'vdb:virtualDatabase.'</message>

        <nameValidation id="vdb.name">
            <message locale="en">Validates the name of nodes having the 'vdb:virtualDatabase' node type.</message>
            <pattern>[a-z]*</pattern>
        </nameValidation>

        <propertyValidation jcrName="vdb:connectionType">
            <message locale="en">Validates the property 'vdb:connectionType' of the 'vdb:virtualDatabase' node type.</message>
            <requiredValidation id="vdb.connectionType.required">
                <message locale="en">The property 'vdb:connectionType' of the 'vdb:virtualDatabase' node type is required.</message>
            </requiredValidation>
        </propertyValidation>
    </nodeValidation>

    <propertyValidation jcrName="ddl:statementOption">
        <message locale="en">Validates the property 'ddl:statementOption' of any node type.</message>
        <valueValidation id="ddl:statementOption.value">
            <message locale="en">The value of property 'ddl:statementOption' is invalid.</message>
            <pattern>[a-zA-Z\-]{0,64}\.[a-zA-Z\-]{0,64}</pattern>
        </valueValidation>
    </propertyValidation>

    <nodeValidation jcrName="vdb:dataRole">
        <message locale="en">Validation rules for the 'vdb:dataRole' node type.</message>
        <childValidation jcrName="vdb:permissions">
            <message locale="en">Validation rules for child node type 'vdb:permissions' of the 'vdb:dataRole' node type.</message>
            <childCountValidation id="vdb.dataRole.permissions.childCount">
                <message locale="en">Validation rule checking child count for node type 'vdb:permission' in the 'vdb:dataRole' node type.
                </message>
                <minValue inclusive="true">0</minValue>
                <minValue inclusive="false">10.5</minValue>
            </childCountValidation>
        </childValidation>
    </nodeValidation>
</validationRuleSet>

=== MarsYun/komodo/komodo-relational/src/main/java/org/komodo/relational/vdb/validation/relationalValidation.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<validationRuleSet
    xmlns:val="http://www.jboss.org/tools/komodo/validation/2015"
    xmlns:ddl="http://www.modeshape.org/ddl/1.0"
    xmlns:vdb="http://www.metamatrix.com/metamodels/VirtualDatabase"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.jboss.org/tools/komodo/validation/2015 http://www.jboss.org/tools/komodo/validation/2015/komodoValidation.xsd"
    xmlns="http://www.jboss.org/tools/komodo/validation/2015">

    <description locale="en">This is the relational model validation file.</description>

    <nodeValidation jcrName="vdb:virtualDatabase">
        <message locale="en">Validation rules for the 'vdb:virtualDatabase' node type.</message>
        <!-- <nameValidation id="vdb.name"> <message locale="en">Validates the name of nodes having the 'vdb:virtualDatabase' node 
            type.</message> <pattern>[a-z]*</pattern> </nameValidation> -->
        <propertyValidation jcrName="vdb:name">
            <message locale="en">Rules that validate the property 'vdb:name' of the 'vdb:virtualDatabase' node type.</message>
            <requiredValidation id="vdb.name.required">
                <message locale="en">The property 'vdb:name' of the 'vdb:virtualDatabase' node type is required.</message>
            </requiredValidation>
        </propertyValidation>

        <propertyValidation jcrName="vdb:version">
            <message locale="en">Rules that validate the property 'vdb:version' of the 'vdb:virtualDatabase' node type.
            </message>
            <requiredValidation id="vdb.version.required">
                <message locale="en">The property 'vdb:version' of the 'vdb:virtualDatabase' node type is required.</message>
            </requiredValidation>
            <valueValidation id="vdb:version.value">
                <message locale="en">The value of property 'vdb:version' is invalid.</message>
                <pattern>[0-9]+</pattern>
            </valueValidation>
        </propertyValidation>

        <propertyValidation jcrName="vdb:originalFile">
            <message locale="en">Rules that validate the property 'vdb:originalFile' of the 'vdb:virtualDatabase' node type.
            </message>
            <requiredValidation id="vdb.originalFile.required">
                <message locale="en">The property 'vdb:originalFile' of the 'vdb:virtualDatabase' node type is required.
                </message>
            </requiredValidation>
        </propertyValidation>
    </nodeValidation>

    <nodeValidation jcrName="vdb:declarativeModel">
        <message locale="en">Validation rules for the 'vdb:declarativeModel' node type.</message>
        <propertyValidation jcrName="mmcore:modelType">
            <message locale="en">Rules that validate the property 'mmcore:modelType' of the 'vdb:virtualDatabase' node type.
            </message>
            <requiredValidation id="declarativeModel.modelType.required">
                <message locale="en">The property 'mmcore:modelType' of the 'vdb:virtualDatabase' node type is required.
                </message>
            </requiredValidation>
        </propertyValidation>
   </nodeValidation>
</validationRuleSet>

=== MarsYun/komodo/komodo-core-tests/src/test/resources/propRequiredRule.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<validationRuleSet
    xmlns:val="http://www.jboss.org/tools/komodo/validation/2015"
    xmlns:ddl="http://www.modeshape.org/ddl/1.0"
    xmlns:vdb="http://www.metamatrix.com/metamodels/VirtualDatabase"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.jboss.org/tools/komodo/validation/2015 http://www.jboss.org/tools/komodo/validation/2015/komodoValidation.xsd"
    xmlns="http://www.jboss.org/tools/komodo/validation/2015">

    <description locale="en">This is a test validation file.</description>
    <description locale="es">Este es un archivo de validación de pruebas.</description>

    <nodeValidation jcrName="vdb:virtualDatabase">
        <message locale="en">Validation rules for a VDB.</message>
        <message locale="es">Las reglas de validación para el tipo de nodo 'vdb:virtualDatabase.'</message>

        <propertyValidation jcrName="vdb:connectionType">
            <message locale="en">Validates a VDB's connection type.</message>
            <requiredValidation id="vdb.connectionType.required">
                <description locale="en">The VDB connection type is required.</description>
            </requiredValidation>
        </propertyValidation>
    </nodeValidation>

</validationRuleSet>
